<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Article;
use App\Models\Articles;

class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Articles::create([
            'user_id' => 1,
            'title' => 'Metode Pengujian System Usability Scale (SUS)',
            'slug' => 'metode-pengujian-system-usability-scale-sus',
            'image' => 'articleFactory.png',
            'content' => '<p>	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel tortor vulputate, auctor eros a, gravida nibh. Mauris lacinia vitae ligula vitae vulputate. Nulla facilisis, diam eu sollicitudin elementum, sem tortor vestibulum ex, facilisis pellentesque ante diam eget justo. Etiam tempor blandit scelerisque. Phasellus dapibus facilisis nulla vitae luctus. Donec nulla velit, ornare in accumsan dapibus, imperdiet vitae velit. Donec pretium nisi egestas consectetur maximus. Duis dictum accumsan dui et placerat. Nunc at magna posuere, volutpat purus sit amet, molestie purus. Maecenas non felis sed odio dictum tempus non consectetur tellus. Ut tempus fringilla dolor in tincidunt. Suspendisse potenti. Nullam consequat libero eget lectus scelerisque viverra. Aliquam lobortis turpis nulla, eu tincidunt eros luctus a. Pellentesque sapien dui, ullamcorper id viverra at, ultrices in velit. Integer in egestas velit. Vestibulum sagittis erat quis iaculis volutpat. In ex orci, accumsan eu gravida in, commodo eu diam. </p><p><br></p><p>	Duis egestas tortor non nisl consequat rutrum. Curabitur hendrerit tellus dui, in rutrum magna interdum eget. In eu elit et tellus malesuada tempor vel ac ante. Quisque justo augue, bibendum a aliquet at, condimentum vitae est. Aliquam erat volutpat. Fusce sit amet risus at tellus cursus porttitor ut ut nunc. Sed tristique rhoncus nibh, ut malesuada lacus ultrices a. Quisque aliquet eget velit sit amet tincidunt. Ut hendrerit congue leo quis auctor. Vivamus sodales feugiat nisl. Vivamus auctor placerat nibh. Curabitur gravida lacinia neque, et accumsan justo vestibulum eu. Donec ullamcorper enim ipsum, ut mollis tellus luctus at. Donec scelerisque lobortis nibh, sit amet ornare ex eleifend id. Donec consectetur nunc at dolor bibendum, sed mattis dui molestie. Quisque eros diam, sagittis ut tellus et, condimentum ultricies ligula. Phasellus rhoncus ac purus non pulvinar. Sed lobortis ante augue, vel aliquet eros viverra sed. Morbi et massa orci. In eleifend lorem ante, vel rhoncus mauris egestas sed. </p><p><br></p><p>	Maecenas varius tempor justo, nec congue sem mattis et. Pellentesque pharetra porta odio nec fringilla. Vestibulum ullamcorper neque id malesuada egestas. Phasellus tincidunt malesuada quam et pharetra. Fusce semper hendrerit mauris vel varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut iaculis risus. Nullam tincidunt justo ut nisl auctor, consectetur sollicitudin libero vestibulum. Pellentesque scelerisque facilisis justo, et pharetra tortor aliquet id. In hendrerit sed urna non varius. Nunc vestibulum mi velit, ac vulputate leo pretium id. Maecenas placerat mattis leo, id aliquet nulla. Nulla facilisi.</p>',
            'status' => 'Public',
        ]);

        Articles::create([
            'user_id' => 1,
            'title' => 'Metode Pengujian Technology Acceptance Model (TAM)',
            'slug' => 'metode-pengujian-technology-acceptance-model-tam',
            'image' => 'articleFactory.png',
            'content' => '<p>	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel tortor vulputate, auctor eros a, gravida nibh. Mauris lacinia vitae ligula vitae vulputate. Nulla facilisis, diam eu sollicitudin elementum, sem tortor vestibulum ex, facilisis pellentesque ante diam eget justo. Etiam tempor blandit scelerisque. Phasellus dapibus facilisis nulla vitae luctus. Donec nulla velit, ornare in accumsan dapibus, imperdiet vitae velit. Donec pretium nisi egestas consectetur maximus. Duis dictum accumsan dui et placerat. Nunc at magna posuere, volutpat purus sit amet, molestie purus. Maecenas non felis sed odio dictum tempus non consectetur tellus. Ut tempus fringilla dolor in tincidunt. Suspendisse potenti. Nullam consequat libero eget lectus scelerisque viverra. Aliquam lobortis turpis nulla, eu tincidunt eros luctus a. Pellentesque sapien dui, ullamcorper id viverra at, ultrices in velit. Integer in egestas velit. Vestibulum sagittis erat quis iaculis volutpat. In ex orci, accumsan eu gravida in, commodo eu diam. </p><p><br></p><p>	Duis egestas tortor non nisl consequat rutrum. Curabitur hendrerit tellus dui, in rutrum magna interdum eget. In eu elit et tellus malesuada tempor vel ac ante. Quisque justo augue, bibendum a aliquet at, condimentum vitae est. Aliquam erat volutpat. Fusce sit amet risus at tellus cursus porttitor ut ut nunc. Sed tristique rhoncus nibh, ut malesuada lacus ultrices a. Quisque aliquet eget velit sit amet tincidunt. Ut hendrerit congue leo quis auctor. Vivamus sodales feugiat nisl. Vivamus auctor placerat nibh. Curabitur gravida lacinia neque, et accumsan justo vestibulum eu. Donec ullamcorper enim ipsum, ut mollis tellus luctus at. Donec scelerisque lobortis nibh, sit amet ornare ex eleifend id. Donec consectetur nunc at dolor bibendum, sed mattis dui molestie. Quisque eros diam, sagittis ut tellus et, condimentum ultricies ligula. Phasellus rhoncus ac purus non pulvinar. Sed lobortis ante augue, vel aliquet eros viverra sed. Morbi et massa orci. In eleifend lorem ante, vel rhoncus mauris egestas sed. </p><p><br></p><p>	Maecenas varius tempor justo, nec congue sem mattis et. Pellentesque pharetra porta odio nec fringilla. Vestibulum ullamcorper neque id malesuada egestas. Phasellus tincidunt malesuada quam et pharetra. Fusce semper hendrerit mauris vel varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut iaculis risus. Nullam tincidunt justo ut nisl auctor, consectetur sollicitudin libero vestibulum. Pellentesque scelerisque facilisis justo, et pharetra tortor aliquet id. In hendrerit sed urna non varius. Nunc vestibulum mi velit, ac vulputate leo pretium id. Maecenas placerat mattis leo, id aliquet nulla. Nulla facilisi.</p>',
            'status' => 'Public',
        ]);


        Articles::create([
            'user_id' => 1,
            'title' => 'Pengertian Usability Testing (Uji kegunaan)',
            'slug' => 'pengertian-usability-testing-uji-kegunaan',
            'image' => 'articleFactory.png',
            'content' => '<p>	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel tortor vulputate, auctor eros a, gravida nibh. Mauris lacinia vitae ligula vitae vulputate. Nulla facilisis, diam eu sollicitudin elementum, sem tortor vestibulum ex, facilisis pellentesque ante diam eget justo. Etiam tempor blandit scelerisque. Phasellus dapibus facilisis nulla vitae luctus. Donec nulla velit, ornare in accumsan dapibus, imperdiet vitae velit. Donec pretium nisi egestas consectetur maximus. Duis dictum accumsan dui et placerat. Nunc at magna posuere, volutpat purus sit amet, molestie purus. Maecenas non felis sed odio dictum tempus non consectetur tellus. Ut tempus fringilla dolor in tincidunt. Suspendisse potenti. Nullam consequat libero eget lectus scelerisque viverra. Aliquam lobortis turpis nulla, eu tincidunt eros luctus a. Pellentesque sapien dui, ullamcorper id viverra at, ultrices in velit. Integer in egestas velit. Vestibulum sagittis erat quis iaculis volutpat. In ex orci, accumsan eu gravida in, commodo eu diam. </p><p><br></p><p>	Duis egestas tortor non nisl consequat rutrum. Curabitur hendrerit tellus dui, in rutrum magna interdum eget. In eu elit et tellus malesuada tempor vel ac ante. Quisque justo augue, bibendum a aliquet at, condimentum vitae est. Aliquam erat volutpat. Fusce sit amet risus at tellus cursus porttitor ut ut nunc. Sed tristique rhoncus nibh, ut malesuada lacus ultrices a. Quisque aliquet eget velit sit amet tincidunt. Ut hendrerit congue leo quis auctor. Vivamus sodales feugiat nisl. Vivamus auctor placerat nibh. Curabitur gravida lacinia neque, et accumsan justo vestibulum eu. Donec ullamcorper enim ipsum, ut mollis tellus luctus at. Donec scelerisque lobortis nibh, sit amet ornare ex eleifend id. Donec consectetur nunc at dolor bibendum, sed mattis dui molestie. Quisque eros diam, sagittis ut tellus et, condimentum ultricies ligula. Phasellus rhoncus ac purus non pulvinar. Sed lobortis ante augue, vel aliquet eros viverra sed. Morbi et massa orci. In eleifend lorem ante, vel rhoncus mauris egestas sed. </p><p><br></p><p>	Maecenas varius tempor justo, nec congue sem mattis et. Pellentesque pharetra porta odio nec fringilla. Vestibulum ullamcorper neque id malesuada egestas. Phasellus tincidunt malesuada quam et pharetra. Fusce semper hendrerit mauris vel varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut iaculis risus. Nullam tincidunt justo ut nisl auctor, consectetur sollicitudin libero vestibulum. Pellentesque scelerisque facilisis justo, et pharetra tortor aliquet id. In hendrerit sed urna non varius. Nunc vestibulum mi velit, ac vulputate leo pretium id. Maecenas placerat mattis leo, id aliquet nulla. Nulla facilisi.</p>',
            'status' => 'Public',
        ]);
    }
}
